package com.example.hongocman.doan2_android.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BAN_DO_MODEL.
 */
public class BanDoModel {

    private long MaDiaDiem;
    private String DiaChi;
    private String LoaiDiaDiem;
    private float latitude;
    private float longitude;
    private Integer MaDanhMuc;

    public BanDoModel() {
    }

    public BanDoModel(long MaDiaDiem) {
        this.MaDiaDiem = MaDiaDiem;
    }

    public BanDoModel(long MaDiaDiem, String DiaChi, String LoaiDiaDiem, float latitude, float longitude, Integer MaDanhMuc) {
        this.MaDiaDiem = MaDiaDiem;
        this.DiaChi = DiaChi;
        this.LoaiDiaDiem = LoaiDiaDiem;
        this.latitude = latitude;
        this.longitude = longitude;
        this.MaDanhMuc = MaDanhMuc;
    }

    public long getMaDiaDiem() {
        return MaDiaDiem;
    }

    public void setMaDiaDiem(long MaDiaDiem) {
        this.MaDiaDiem = MaDiaDiem;
    }

    public String getDiaChi() {
        return DiaChi;
    }

    public void setDiaChi(String DiaChi) {
        this.DiaChi = DiaChi;
    }

    public String getLoaiDiaDiem() {
        return LoaiDiaDiem;
    }

    public void setLoaiDiaDiem(String LoaiDiaDiem) {
        this.LoaiDiaDiem = LoaiDiaDiem;
    }

    public float getLatitude() {
        return latitude;
    }

    public void setLatitude(float latitude) {
        this.latitude = latitude;
    }

    public float getLongitude() {
        return longitude;
    }

    public void setLongitude(float longitude) {
        this.longitude = longitude;
    }

    public Integer getMaDanhMuc() {
        return MaDanhMuc;
    }

    public void setMaDanhMuc(Integer MaDanhMuc) {
        this.MaDanhMuc = MaDanhMuc;
    }

}
