package com.example.hongocman.doan2_android.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.hongocman.doan2_android.models.LoaiDanhMucModel;
import com.example.hongocman.doan2_android.models.DanhMucModel;
import com.example.hongocman.doan2_android.models.HinhAnhModel;
import com.example.hongocman.doan2_android.models.BanDoModel;

import com.example.hongocman.doan2_android.models.LoaiDanhMucModelDao;
import com.example.hongocman.doan2_android.models.DanhMucModelDao;
import com.example.hongocman.doan2_android.models.HinhAnhModelDao;
import com.example.hongocman.doan2_android.models.BanDoModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loaiDanhMucModelDaoConfig;
    private final DaoConfig danhMucModelDaoConfig;
    private final DaoConfig hinhAnhModelDaoConfig;
    private final DaoConfig banDoModelDaoConfig;

    private final LoaiDanhMucModelDao loaiDanhMucModelDao;
    private final DanhMucModelDao danhMucModelDao;
    private final HinhAnhModelDao hinhAnhModelDao;
    private final BanDoModelDao banDoModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loaiDanhMucModelDaoConfig = daoConfigMap.get(LoaiDanhMucModelDao.class).clone();
        loaiDanhMucModelDaoConfig.initIdentityScope(type);

        danhMucModelDaoConfig = daoConfigMap.get(DanhMucModelDao.class).clone();
        danhMucModelDaoConfig.initIdentityScope(type);

        hinhAnhModelDaoConfig = daoConfigMap.get(HinhAnhModelDao.class).clone();
        hinhAnhModelDaoConfig.initIdentityScope(type);

        banDoModelDaoConfig = daoConfigMap.get(BanDoModelDao.class).clone();
        banDoModelDaoConfig.initIdentityScope(type);

        loaiDanhMucModelDao = new LoaiDanhMucModelDao(loaiDanhMucModelDaoConfig, this);
        danhMucModelDao = new DanhMucModelDao(danhMucModelDaoConfig, this);
        hinhAnhModelDao = new HinhAnhModelDao(hinhAnhModelDaoConfig, this);
        banDoModelDao = new BanDoModelDao(banDoModelDaoConfig, this);

        registerDao(LoaiDanhMucModel.class, loaiDanhMucModelDao);
        registerDao(DanhMucModel.class, danhMucModelDao);
        registerDao(HinhAnhModel.class, hinhAnhModelDao);
        registerDao(BanDoModel.class, banDoModelDao);
    }
    
    public void clear() {
        loaiDanhMucModelDaoConfig.getIdentityScope().clear();
        danhMucModelDaoConfig.getIdentityScope().clear();
        hinhAnhModelDaoConfig.getIdentityScope().clear();
        banDoModelDaoConfig.getIdentityScope().clear();
    }

    public LoaiDanhMucModelDao getLoaiDanhMucModelDao() {
        return loaiDanhMucModelDao;
    }

    public DanhMucModelDao getDanhMucModelDao() {
        return danhMucModelDao;
    }

    public HinhAnhModelDao getHinhAnhModelDao() {
        return hinhAnhModelDao;
    }

    public BanDoModelDao getBanDoModelDao() {
        return banDoModelDao;
    }

}
