package com.example.hongocman.doan2_android.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HINH_ANH_MODEL.
 */
public class HinhAnhModel {

    private long MaHinhAnh;
    private String TieuDe;
    private String DuongDan;
    private int MaDanhMuc;

    public HinhAnhModel() {
    }

    public HinhAnhModel(long MaHinhAnh) {
        this.MaHinhAnh = MaHinhAnh;
    }

    public HinhAnhModel(long MaHinhAnh, String TieuDe, String DuongDan, int MaDanhMuc) {
        this.MaHinhAnh = MaHinhAnh;
        this.TieuDe = TieuDe;
        this.DuongDan = DuongDan;
        this.MaDanhMuc = MaDanhMuc;
    }

    public long getMaHinhAnh() {
        return MaHinhAnh;
    }

    public void setMaHinhAnh(long MaHinhAnh) {
        this.MaHinhAnh = MaHinhAnh;
    }

    public String getTieuDe() {
        return TieuDe;
    }

    public void setTieuDe(String TieuDe) {
        this.TieuDe = TieuDe;
    }

    public String getDuongDan() {
        return DuongDan;
    }

    public void setDuongDan(String DuongDan) {
        this.DuongDan = DuongDan;
    }

    public int getMaDanhMuc() {
        return MaDanhMuc;
    }

    public void setMaDanhMuc(int MaDanhMuc) {
        this.MaDanhMuc = MaDanhMuc;
    }

}
